#!/bin/bash 

server=$1
branch=$2

echo "DEPLOY"
ssh $server <<REMOTE
cd /root/botland

# checkout
git fetch
git reset --hard $branch

# make sure redis is on
service redis-server start

# install deps
aptitude -y install alex libghc-zlib-dev libghc-zlib-bindings-dev
cabal install --only-dependencies

# compile
echo 'COMPLING!'


REMOTE


