#!/bin/bash 

server=$1
branch=$2

echo "DEPLOY"
ssh $server <<REMOTE
cd /root/botland

# checkout
git fetch
git reset --hard $branch

# make sure redis is on
service redis-server start

# install deps
# apt-get -y install alex libghc-zlib-dev libghc-zlib-bindings-dev uuid uuid-dev

# slow, but accurate
# cabal update 
# cabal install --only-dependencies

# compile (use runghc. I couldn't get it to compile before)
ghc --make Api.hs

# run
cp -f server/botland.conf /etc/init/botland.conf
stop botland
start botland

REMOTE


